---
title: "About me"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Education

**Columbia University Mailman School of Public Health**
Master of Public Health | Sociomedical Sciences, Certificate in Applied Biostatistics
						       
**University of Maryland - College Park**	
Bachelor of Arts | Major in Psychology

## Professional Experience

Global Mental Health Program | WHO-Columbia Collaborating Center                                         June 2020-Present
Graduate Research Assistant                      Supervisor: Dr. Kathleen Pike                       		      New York, NY
-Engage with World Health Organization (WHO) collaborating stakeholders in the Netherlands, Japan, and Switzerland to develop a systematic literature review for translation into WHO mental health in the workplace intervention guidelines.  
-Develop search terminology for implementation in collection and evaluation of over 200 academic articles to compile scoping review of return to work interventions for mental health in the workplace. 
-Provide technical writing assistance by drafting and editing manuscript for publication in an academic journal covering mental health interventions in Kenya.

Columbia University | School of Nursing 		                                                                          March 2020 – Present Graduate Research Assistant		 Principal Investigator: Dr. Allison Norful                   	      New York, NY
•	Provide technical writing support by drafting, editing, and proofreading manuscripts covering healthcare policy, healthcare provider burnout, and communication methods for publication in academic journals as a second and third author.
•	Compose online research surveys using Qualtrics for implementation of data collection of over 200 research participants.
•	Prepare documentation and correspondence for Institutional Review Board (IRB) approval. 

Columbia University | Mailman School of Public Health	                                                                 July 2020 – Present Graduate Teaching Assistant	            Course: Introduction to Public Health                                      New York, NY
•	Evaluate and provide detailed feedback for over 100 student essay submissions.
•	Assist with class programming and aided students in understanding foundational public health concepts 
•	Participate in live sessions with students to discuss course material and facilitate discussion. 

RI Resilience Lab | Brown University    							   March 2017-August 2019
Clinical Research Assistant	            Principal Investigator: Dr. Nicole Nugent                                Providence, RI
•	Conducted clinical, semi-structured interviews with 5+ high-risk adolescents per week hospitalized for suicidal ideation at Bradley Hospital, Rhode Island’s children’s psychiatric facility. Interviews included the Clinician-Administered PTSD Scale for DSM-5 For Children and Adolescents (CAPS-CA5) and Kiddie Schedule for Affective Disorders (KSADS)
•	Screened medical charts, recruited, and obtained informed research consent from adolescents and their parents for a longitudinal, NIH-funded R01 study.
•	Conducted risk assessments for adolescent and adult research participants to determine safety concerns. 
•	Supported study protocol by drafting amendments and annual reports for Institutional Review Board (IRB) submission and preparing progress and milestone reports for NIH.
•	Managed, organized, cleaned, and tracked confidential project data, assisted in procuring genetic samples. 
•	Implemented in-vivo data collection methods such as the Electronically Activated Recorder (EAR) and Ecological Momentary Assessment (EMA) on study devices.
•	Collaborated with three labs including computer science Co-Investigators to implement Online Social Networking (OSN) download script and labs involving psychophysiological methodology.




Rhode Island Hospital (RIH) 		                                                             		  May 2016 – January 2017
Clinical Research Assistant	     Principal Investigator: Dr. Colin Harrington                                  Providence, RI
•	Ensured successful enrollment of 180 participants for an NIH multi-site suicide risk screening study, performed quality assessment to ensure successful Internal Review Board (IRB) approval. 
•	Conducted comprehensive suicide risk/depression screening interviews utilizing a variety of measures with 180 medical patients in coordination with study objectives.
•	Provided technical writing support by drafting amendments for submission to the Rhode Island Hospital IRB. 

EF Education First     					      			           	     
Teacher								                    	   Shanghai, China/Washington, DC
•	Taught English as a second language to over 200+ Mandarin-speaking students ages 4-18 and international students ages 14-84.
•	Developed and led trainings for both incoming and experienced teachers, focused on skill development.
•	Created lesson plans for three levels of English language fluency learning and a range of ages. 


## Things to know 

I'm slowly getting better at Data Science.

## Interests

Running