---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

# Examples of Plotly

```{r include = FALSE}
library(tidyverse)
library(ggplot2)
library(p8105.datasets)
library(plotly)
```

```{r message = FALSE, include = FALSE}
data("instacart")

instacart = 
  instacart %>% 
  slice_sample(n = 10000)
```


```{r warning = FALSE}
yax_title = list(title = "Number of Purchases")
xax_title = list(title = "Instacart Departments")

purchase_bar = 
  instacart %>%  
  filter(department != "missing") %>% 
  count(department) %>% 
  mutate(
    department = fct_reorder(department, n)
    ) %>% 
  plot_ly(x = ~department, y = ~n, color = ~department, colors = "viridis", type = "bar") %>% 
  layout(yaxis = yax_title, xaxis = xax_title)

purchase_bar
```

```{r message = FALSE}
yord_title = list(title = "Order Number")
xord_title = list(title = "Days Since Prior Order")

time_order = 
  instacart %>%  
  group_by(order_hour_of_day) %>% 
  plot_ly(x = ~days_since_prior_order, y = ~order_number, color = ~department, colors = "viridis", type = "scatter") %>% 
   layout(yaxis = yord_title, xaxis = xord_title)

time_order
```

```{r}
y_title = list(title = "Number of Orders")
x_title = list(title = "Hour of the Day (Military Time)")

hour_track = 
  instacart %>%  
  group_by(order_hour_of_day) %>%
  plot_ly(
    x = ~order_hour_of_day, 
    colors = "viridis", 
    type = "histogram"
    ) %>% 
   layout(yaxis = y_title, xaxis = x_title)

hour_track
```

